# -*- coding: utf-8 -*-
"""data_leakage_decision_tree_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl-_gfl1TMCpvOKYAfYWIJOsNcV-Uc11

# **Identify Data Leakage in Machine Learning Models**

## <a id='objectives'></a>[Objectives](#toc)

* Understand how to preprocess real-world datasets by identifying critical features prone to leakage and mapping data to ensure ethical and practical use.
* Build and evaluate machine learning models such as decision trees and random forests, with a focus on preventing data leakage and interpreting results using metrics such as accuracy, recall, and confusion matrices.
* Learn how to recognize the signs of data leakage and implement techniques to mitigate its impact, ensuring model validity.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import export_text, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

sns.set_context('notebook')
sns.set_style('white')

def display_feature_importances(model, feature_names):
    """
    Displays feature importances for a Decision Tree or Random Forest model.

    Parameters:
    - model: A trained DecisionTreeClassifier or RandomForestClassifier from sklearn.
    - feature_names: List of feature names corresponding to the columns in X_train.

    Returns:
    - A DataFrame sorted by feature importance.
    """
    # Feature importances from the model
    feature_importance = model.feature_importances_

    # Creating a DataFrame to display feature names and their importance
    feature_importance_df = pd.DataFrame({'Feature': feature_names,
        'Importance': feature_importance})

    # Sort by importance (highest to lowest)
    feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

    # Plot the feature importance
    plt.figure(figsize=(10, 6))
    plt.barh(feature_importance_df['Feature'], feature_importance_df['Importance'])
    plt.xlabel('Importance')
    plt.ylabel('Feature')
    plt.title('Feature Importance')
    plt.gca().invert_yaxis()  # To show the highest importance on top
    plt.show()

    # Return the sorted DataFrame
    return feature_importance_df

class TreeSplanerClassifier:
    """
    A class to extract and convert decision rules from a trained decision tree into natural language.
    """

    def __init__(self, clf, feature_names=None, target_names=None):
        self.clf = clf
        # Explicitly check if feature_names or target_names are None
        if feature_names is None:
            self.feature_names = [f"feature_{i}" for i in range(clf.tree_.n_features)]
        else:
            self.feature_names = feature_names

        if target_names is None:
            self.target_names = [f"class_{i}" for i in range(clf.tree_.n_classes)]
        else:
            self.target_names = target_names

        # Cache commonly used tree attributes
        self.children_left = clf.tree_.children_left
        self.children_right = clf.tree_.children_right
        self.feature = clf.tree_.feature
        self.threshold = clf.tree_.threshold
        self.value = clf.tree_.value

    def find_paths_from_root(self, node=0, path=None, all_paths=None):
        """Recursively finds all paths from the root node to each leaf node."""
        if path is None:
            path = []
        if all_paths is None:
            all_paths = []

        path.append(node)

        # Check if it is a leaf node
        if self.children_left[node] == -1 and self.children_right[node] == -1:
            all_paths.append(list(path))
        else:
            # Recursively explore the left and right children
            if self.children_left[node] != -1:
                self.find_paths_from_root(self.children_left[node], path, all_paths)
            if self.children_right[node] != -1:
                self.find_paths_from_root(self.children_right[node], path, all_paths)

        path.pop()

        return all_paths

    def decision_tree_to_text(self):
        """
        Converts the tree's structure into a natural language description of its decision rules.
        """
        all_paths = self.find_paths_from_root()
        branch = "If "
        number_paths = len(all_paths)


        for p, path in enumerate(all_paths):
            branch += " ("
            for l, node in enumerate(path):



                # Determine inequality direction based on child position
                if node in self.children_right:
                    eq = ">"


                elif node==0 and  path[l+1] in  self.children_right:
                    eq = ">"

                else:
                    eq = "<="

                if l != len(path) - 1:
                    branch += f"{self.feature_names[self.feature[node]]} {eq} {round(self.threshold[node], 2)} and "
                else:
                    target_index=np.argmax(self.value[node, 0, :])

                    predicted_class = self.target_names[target_index]
                    probability_class=round(self.clf.tree_.value[node,0,target_index],3)
                    branch += f"{self.feature_names[self.feature[node]]} {eq} {round(self.threshold[node], 2)} then class is {predicted_class}  with probability of {probability_class}"
            branch += " )" + (" or" if p != number_paths - 1 else "")
        return branch


    def build_text_prediction(self, samples):
        """
        Generates natural language predictions for specific samples.
        """
        branches = []

        for sample in samples:
            sample = np.array(sample).reshape(1, -1)
            node_indicator = self.clf.decision_path(sample)
            predicted_index=int(self.clf.predict(sample)[0])
            predicted_class = self.target_names[predicted_index]

            probability_class=np.round(self.clf.predict_proba(sample)[0][predicted_index],3)

            branch = ""

            # Get the path for the current sample
            path = node_indicator.indices
            for n, node in enumerate(path):
                # Determine inequality direction based on child position
                if node in self.children_right:
                    eq = ">"
                else:
                    eq = "<="

                if n != len(path) - 1:
                    branch += f"{self.feature_names[self.feature[node]]} {eq} {round(self.threshold[node], 2)} and "
                else:
                    branch += f"{self.feature_names[self.feature[node]]} {eq} {round(self.threshold[node], 2)} therefore the class is {predicted_class} with probability of {probability_class}"

            branches.append(branch)

        return branches

    def branch_impurity(self):
        all_paths=self.find_paths_from_root()
        node_impurity=self.clf.tree_.impurity
        feature=self.feature
        branch_impurity=""
        for p, path in enumerate(all_paths):
            branch_impurity+=f" For branch {p+1} "

            for node in path:

                branch_impurity+=f" for split  {node } and feature {self.feature_names[feature[node]]} impurity is {round(node_impurity[node],3)} "
        return branch_impurity

df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/6exL12iQvqfWQgXniFXM4g/Predict%20Student%20Dropout%20and%20Academic%20Success.csv", delimiter=";")
df.head()

"""The dataset contains information about students’ academic performance, demographics, and institutional factors. The output showing the shape of the dataset (rows and columns) helps understand the size of the data available for analysis. A large number of rows means there are many student records, while the number of columns indicates the features used to predict the target variable. The list of columns confirms the presence of variables related to academic performance, socio-economic background, and institutional attributes. These features will later be used by machine learning models to predict whether a student will Dropout, remain Enrolled, or Graduate."""

print("\nShape of the dataset (rows, columns):", df.shape)

print("\nColumns in the dataset:", df.columns)

df['Target'].value_counts()

"""This output reveals the distribution of students among the three classes: Dropout, Enrolled, and Graduate. A count plot helps visualize whether the dataset is balanced or imbalanced. If one class (such as Graduate) appears much more frequently than others, the model may become biased toward predicting that class. Understanding this distribution is important because class imbalance can influence model performance and evaluation metrics."""

sns.countplot(x='Target', data=df)

"""The bar chart shows the distribution of the Target variable, which represents student outcomes: Graduate, Dropout, and Enrolled. The Graduate category has the highest number of observations (around 2,200), indicating that most students successfully complete their studies. The Dropout category is the second largest with approximately 1,400 students, while Enrolled has the smallest count with about 800 students who are still continuing their education. This distribution indicates a class imbalance in the dataset, as the number of graduates is significantly higher than the other categories. Overall, the dataset contains roughly 4,400 observations, and although the majority of students graduate, the dropout rate is still considerable, suggesting that student retention is an important issue to analyze further."""

df.describe()

df.nunique()

data = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/xmqtgnRT0GpQnTsjJHDVTw/mapped-dropout-data.csv')
data.head()

data = data.drop('Unnamed: 0', axis = 1)
data.head()

# Get all the categorical columns and exlude the numeric ones
cat_columns = data.columns.to_list()

num_columns = ['Previous qualification (grade)', 'Admission grade',
               'Curricular units 1st sem (grade)', 'Curricular units 2nd sem (grade)']    # List of numerical columns

for col in num_columns:
    cat_columns.remove(col)   # Remove the numerical columns from cat_columns

cat_columns

for column in cat_columns:
    plt.figure(figsize=(8, 6))
    sns.countplot(x='Target', hue=column, data=data)
    plt.title(f'Count of {column} by Target')
    plt.ylabel('Count')
    plt.xlabel('Target')
    plt.xticks(rotation=0)
    plt.show()

"""These plots show how different categorical factors relate to student outcomes. For example, some categories may have a higher proportion of dropouts, while others may show more graduates. This visual analysis helps identify patterns and potential predictors. If a certain category consistently shows higher dropout rates, it indicates that the feature may have predictive importance in the model."""

for column in num_columns:
    plt.figure(figsize=(8, 6))
    for target in data['Target'].unique():
        subset = data[data['Target'] == target]
        sns.histplot(subset[column], kde=True, label=target, element="step", alpha=0.6)
    plt.title(f'Distribution of {column} by Target')
    plt.xlabel(column)
    plt.ylabel('Count')
    plt.legend(title='Target')
    plt.show()

"""These histograms compare how numerical variables are distributed across different target classes. For example, students who graduate may generally have higher admission or qualification grades, while those who drop out may show lower values. Observing these distributions helps identify which variables might strongly influence the model’s predictions."""

y = data['Target']
y.head()

X = data.drop('Target',axis=1)
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

def decisonTreeClassifier(X_train, y_train, X_test, y_test):
    clf = DecisionTreeClassifier(random_state=42)

    # Train the model on the training set
    clf.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = clf.predict(X_test)

    return y_pred, clf

y_pred, clf = decisonTreeClassifier(X_train, y_train, X_test, y_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}\n")
print(f"Confusion Matrix: \n{conf_matrix}\n")
print(f"Classification Report: \n{class_report}")

"""The Decision Tree model achieved an overall accuracy of about 69.38%, meaning that the model correctly predicted the student outcome for roughly 69% of the test samples. From the confusion matrix, we can see that 202 dropout cases, 76 enrolled students, and 336 graduates were correctly classified. However, there are also several misclassifications. For example, some dropout students were predicted as enrolled or graduate, and many enrolled students were misclassified as dropout or graduate, showing that the model struggles to clearly distinguish the Enrolled category.

The classification report provides deeper insight into model performance. The Graduate class has the best performance with precision of 0.85 and recall of 0.75, indicating that the model is very good at identifying students who graduate. The Dropout class shows moderate performance with precision of 0.68 and recall of 0.71, meaning the model identifies dropout cases reasonably well. However, the Enrolled class has the weakest performance with precision of 0.40 and recall of 0.50, suggesting the model frequently confuses enrolled students with the other categories. Overall, while the model performs fairly well for graduates and moderately for dropouts, it has difficulty accurately predicting students who remain enrolled.
"""

disp = ConfusionMatrixDisplay(confusion_matrix=conf_matrix,display_labels=clf.classes_)
disp.plot()
plt.show()

"""The confusion matrix visualizes the performance of the Decision Tree model by comparing the true labels with the predicted labels. The diagonal values represent correct predictions. The model correctly classified 202 Dropout, 76 Enrolled, and 336 Graduate students. However, there are several misclassifications. For example, 52 Dropout students were predicted as Enrolled and 30 as Graduate, while 44 Enrolled students were predicted as Dropout and 31 as Graduate. Similarly, 52 Graduate students were misclassified as Dropout and 62 as Enrolled.

The model performs best in predicting the Graduate class since it has the highest number of correct predictions. The Dropout class shows moderate performance with some confusion with other categories. The Enrolled class has the highest misclassification, indicating that the model finds it difficult to distinguish enrolled students from those who drop out or graduate.
"""

print("Feature name ", X_train.columns, "\n")
print("Feature importance ", clf.feature_importances_)

"""The feature importance output shows how much each feature contributes to the predictions made by the Decision Tree model. Each value represents the relative importance of that feature in reducing classification error when the tree splits the data. From the results, “Curricular units 2nd sem (approved)” has the highest importance value (0.343), which is significantly larger than all other features. This indicates that the model relies heavily on this feature to make predictions. Other relatively important features include Admission grade, Age at enrollment, Tuition fees up to date, and Curricular units 2nd sem (grade), which also contribute to predicting student outcomes. However, the extremely high importance of “Curricular units 2nd sem (approved)” suggests possible data leakage, because this feature is closely related to the final academic outcome. Therefore, while the model appears to perform well, its predictions may be influenced by information that would not normally be available at the time of prediction."""

feature_importance_trees = display_feature_importances(clf, X_train.columns)

"""The feature “Curricular units 2nd sem (approved)” appears with extremely high importance compared to other features. This indicates that the decision tree relies heavily on this variable to make predictions. While high importance normally suggests strong predictive power, such extreme dominance raises concerns about data leakage, because the feature may contain information that is directly related to the outcome.

This feature reflects the number of courses a student passed in the second semester. However, if a student drops out early, they naturally have zero approved courses, which directly signals the dropout outcome. Therefore, the model is indirectly using the final result to predict itself. This phenomenon is known as data leakage, where the model has access to information that would not be available at prediction time. As a result, the high accuracy observed earlier may be misleading.
"""

def randomForestClassifier(X_train, y_train, X_test, y_test):
    random_forest_model = RandomForestClassifier(random_state=42,n_estimators=100)

    # Train the model on the training set
    random_forest_model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = random_forest_model.predict(X_test)

    return y_pred, random_forest_model

y_pred, random_forest_model = randomForestClassifier(X_train, y_train, X_test, y_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}\n")
print(f"Confusion Matrix: \n{conf_matrix}\n")
print(f"Classification Report: \n{class_report}")

"""The Random Forest model achieved an overall accuracy of 80%, which is higher than the previous Decision Tree model. This means the model correctly predicted the student outcomes for about 80% of the test data. From the confusion matrix, the model correctly classified 218 Dropout, 67 Enrolled, and 423 Graduate students. However, there are still some misclassifications, such as 34 Dropout students predicted as Enrolled and 32 as Graduate, while 37 Enrolled students were predicted as Dropout and 47 as Graduate.

The classification report shows that the Graduate class has the best performance with precision of 0.84 and recall of 0.94, indicating that the model is very effective at identifying students who graduate. The Dropout class also shows good performance with precision of 0.81 and recall of 0.77. However, the Enrolled class still has the lowest performance with precision of 0.59 and recall of 0.44, meaning the model continues to struggle in accurately distinguishing enrolled students from the other categories. Overall, the Random Forest model performs better than the Decision Tree model, particularly in predicting graduates and dropouts.
"""

disp = ConfusionMatrixDisplay(confusion_matrix=conf_matrix,display_labels=random_forest_model.classes_)
disp.plot()
plt.show()

"""The confusion matrix shows the performance of the Random Forest model by comparing the actual student outcomes with the predicted outcomes. The diagonal values represent the correct predictions. The model correctly classified 218 Dropout, 67 Enrolled, and 423 Graduate students. However, some misclassifications are present. For example, 34 Dropout students were predicted as Enrolled and 32 as Graduate, while 37 Enrolled students were predicted as Dropout and 47 as Graduate. Additionally, a small number of Graduate students were misclassified as Dropout (14) and Enrolled (13).

The model performs very well in predicting the Graduate class, as it has the highest number of correct predictions and very few errors. The Dropout class also shows good prediction accuracy. However, similar to the previous model, the Enrolled class has more misclassifications, indicating that the model still finds it difficult to clearly distinguish students who remain enrolled from those who drop out or graduate.
"""

feature_importance_rf = display_feature_importances(random_forest_model, X_train.columns)

"""The feature importance chart now shows a more balanced distribution of importance across multiple variables compared to the earlier model. The most influential predictors are mainly related to academic performance, particularly Curricular units 2nd sem (approved), Curricular units 2nd sem (grade), Curricular units 1st sem (approved), and Curricular units 1st sem (grade). These features indicate that both the number of courses passed and the grades achieved in the first and second semesters strongly influence whether a student will graduate, remain enrolled, or drop out.

Another important factor is Admission grade, which suggests that students’ previous academic performance before entering university plays a significant role in predicting their success. Additionally, Tuition fees up to date appears relatively important, indicating that financial stability may affect a student’s ability to continue their studies. In contrast, several features such as Marital status, International status, and Displaced status have very low importance values, meaning they contribute only slightly to the model’s predictions. The model now relies on multiple meaningful predictors rather than depending heavily on a single feature.
"""

data = data.drop('Curricular units 2nd sem (approved)', axis=1)
data.columns

"""The output shows the list of all columns (features) present in the dataset after preprocessing. These features include demographic information, academic background, financial status, and macro-economic indicators, which are used to predict the Target variable (student outcome: Dropout, Enrolled, or Graduate). For example, variables such as Admission grade, Previous qualification grade, and Curricular units grades represent academic performance, while Scholarship holder, Tuition fees up to date, and Debtor describe the student’s financial situation. Other features like Age at enrollment, Gender, and Parents’ occupation or qualification provide demographic and socio-economic context. Additionally, external factors such as Unemployment rate, Inflation rate, and GDP capture the economic environment that may indirectly affect student success. Overall, these features together form the input variables used by the machine learning model to predict the final Target outcome."""

# After dropping the column we begin the model training
y = data['Target']
y.head()

X = data.drop('Target',axis=1)
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

y_pred, clf = decisonTreeClassifier(X_train, y_train, X_test, y_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}\n")
print(f"Confusion Matrix: \n{conf_matrix}\n")
print(f"Classification Report: \n{class_report}")

"""The model achieved an overall accuracy of about 63.8%, meaning it correctly predicted the student outcome for roughly 64% of the test samples. According to the confusion matrix, the model correctly classified 190 Dropout, 60 Enrolled, and 315 Graduate students. However, several misclassifications occurred. For example, 63 Dropout students were predicted as Enrolled and 31 as Graduate, while 45 Enrolled students were predicted as Dropout and 46 as Graduate. Additionally, 58 Graduate students were misclassified as Dropout and 77 as Enrolled.

The classification report shows that the Graduate class performs the best, with a precision of 0.80 and recall of 0.70, indicating the model is fairly good at identifying students who graduate. The Dropout class has moderate performance with precision of 0.65 and recall of 0.67. However, the Enrolled class has the weakest performance, with precision of 0.30 and recall of 0.40, showing that the model struggles to correctly distinguish currently enrolled students from those who drop out or graduate. The results suggest that while the model can reasonably predict graduates and dropouts, it has difficulty accurately identifying the enrolled category.
"""

feature_importance_trees = display_feature_importances(clf, X_train.columns)

"""The third feature importance result shows that “Curricular units 1st sem (approved)” is the most important predictor in the model. This indicates that student performance in the first semester is a key factor in predicting whether a student will graduate, remain enrolled, or drop out, making it an important early indicator of academic success. The second most important feature is “Curricular units 2nd sem (grade)”, showing that the quality of performance in later semesters also influences the outcome. Additionally, Admission grade and Tuition fees up to date remain important predictors, suggesting that both previous academic performance and financial stability play a significant role in student success."""

data = data.drop(['Curricular units 1st sem (approved)', 'Curricular units 2nd sem (grade)', 'Curricular units 1st sem (grade)', 'Tuition fees up to date', 'Curricular units 2nd sem (evaluations)', 'Curricular units 1st sem (enrolled)', 'Curricular units 2nd sem (enrolled)', 'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (without evaluations)'], axis=1)

# After dropping the column we begin the model training
y = data['Target']
y.head()

X = data.drop('Target',axis=1)
X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

y_pred, clf = decisonTreeClassifier(X_train, y_train, X_test, y_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}\n")
print(f"Confusion Matrix: \n{conf_matrix}\n")
print(f"Classification Report: \n{class_report}")

"""The model achieved an accuracy of about 50.4%, which indicates relatively low predictive performance. From the confusion matrix, the model correctly classified 141 Dropout, 39 Enrolled, and 266 Graduate students. However, there are many misclassifications. For example, 101 Dropout students were predicted as Graduate, and 92 Graduate students were predicted as Dropout or Enrolled.

The classification report shows that the Graduate class performs better than the others with precision 0.61 and recall 0.59, while the Dropout class has moderate performance with precision 0.51 and recall 0.50. The Enrolled class performs the worst with precision 0.23 and recall 0.26, meaning the model struggles to correctly identify enrolled students. The results suggest that this model is less effective compared to the previous models and has difficulty distinguishing between the three student outcome categories.
"""

feature_importance_trees = display_feature_importances(clf, X_train.columns)

"""The feature importance analysis shows that Admission grade is the most influential predictor in the model, followed by Previous qualification (grade). This indicates that a student’s previous academic performance is the strongest factor in predicting their future academic outcome. Another important variable is Age at enrollment, suggesting that the age at which a student starts their studies can influence their success or continuation in the program. Additionally, Mother’s occupation and Father’s occupation also have noticeable importance, showing that family background and socio economic factors play a role in student outcomes. In contrast, features such as Nationality, International status, Educational special needs, and Daytime/evening attendance have very low importance, meaning they contribute little to the model’s predictions. The results suggest that academic history and some socio-economic factors are the key drivers of the model’s decisions."""

y_pred, random_forest_model = randomForestClassifier(X_train, y_train, X_test, y_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}\n")
print(f"Confusion Matrix: \n{conf_matrix}\n")
print(f"Classification Report: \n{class_report}")

"""The model achieved an overall accuracy of about 62%, meaning it correctly predicted the outcomes for around 620 out of 885 students. From the confusion matrix, the model correctly classified 172 Dropout, 19 Enrolled, and 358 Graduate students. However, several misclassifications occurred, such as 96 Dropout students predicted as Graduate and 83 Enrolled students predicted as Graduate.

According to the classification report, the Graduate class performs the best with precision 0.67 and recall 0.80, indicating the model is good at identifying students who graduate. The Dropout class shows moderate performance with precision 0.59 and recall 0.61. However, the Enrolled class performs poorly with precision 0.35 and recall 0.13, meaning the model struggles to correctly identify students who remain enrolled. The model predicts graduates reasonably well, but has difficulty distinguishing enrolled students from the other categories.

### <a id='tree-visualization'></a>[Tree visualization](#toc)
"""

plt.figure(figsize=(20,10))  # Adjust the size for better readability
plot_tree(clf, feature_names=X_test.columns, class_names=clf.classes_,max_depth=2, filled=True, rounded=True)
plt.show()

"""### <a id='decision-tree-insights'></a>[Tree insights](#toc)

1. **Root node**:  
   - The tree starts with **"Scholarship holder <= 0.5"** as the primary split, dividing students based on whether they hold a scholarship.

2. **Left branch (No scholarship)**:  
   - Key splits include **"Age at enrollment <= 22.5"** and **"Debtor <= 0.5"**, leading to classifications such as **Dropout** and **Graduate**.

3. **Right branch (With Scholarship)**:  
   - Further splits on **"Unemployment rate <= 8.25"** and **Debtor status** predict **Graduate** outcomes with lower impurity.

4. **Leaf nodes**:  
   - Final outcomes (e.g., **Dropout** or **Graduate**) are determined based on these features, with **Gini index** values indicating the confidence of each classification.

The tree identifies **Scholarship holder**, **Age at enrollment**, and **Unemployment rate** as the most influential features for predicting student outcomes.

The Decision Tree visualization shows how the model predicts whether a student will Dropout, Enrolled, or Graduate based on different conditions. The root node starts with the feature Scholarship holder, indicating that whether a student receives a scholarship is the first and most important decision point. If the student is not a scholarship holder, the tree further checks Age at enrollment, suggesting that younger and older students may have different academic outcomes. Another important factor in the tree is Debtor status, which indicates that students with unpaid fees or debts may have a higher risk of dropping out.

On the other branch, the model considers Unemployment rate and Course, showing that external economic conditions and the chosen course can also influence student outcomes. In most branches, the predicted class is Graduate, which suggests that the dataset contains a higher number of graduates compared to other categories. The decision tree highlights that financial status (scholarship or debt), age at enrollment, and economic factors play an important role in predicting student success.
"""

tree_rules = export_text(clf, feature_names=list(X_train.columns),max_depth=2)
print(tree_rules)

"""The decision tree rules show how the model makes predictions step by step using different conditions. The first and most important split is Scholarship holder. If a student does not have a scholarship (≤ 0.50), the model then checks Age at enrollment. For students aged 22.5 years or younger, the next important factor is whether the student is a debtor, indicating that financial obligations can influence the likelihood of dropping out or graduating. For students older than 22.5, the model again evaluates the debtor status, showing that financial stability plays an important role for this group as well.

If the student has a scholarship (> 0.50), the model instead considers the Unemployment rate in the economy. When unemployment is ≤ 8.25, the next decision is based on the Course, suggesting that different courses may have different success rates. If unemployment is higher than 8.25, the model again checks the debtor status. The tree indicates that scholarship status, age at enrollment, debtor status, unemployment rate, and course are key factors influencing the prediction of student outcomes.

### <a id='tree-visualization-using-treesplainer'></a>[Tree visualization using TreeSplainer](#toc)  

The `TreeSplanerClassifier` class takes a trained **decision tree** and provides human readable insights by:

- Extracting decision rules in text format.  
- Generating predictions with explanations for specific samples.  
- Displaying branch impurity information to analyze split quality.
"""

# Separate features and target
X = data.drop('Target', axis=1)
y = data['Target']

# Encode the target variable
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=0)

# Train a Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train, y_train)

"""After training the decision tree classifier, let's start by initializing `TreeSplanerClassifier` object. Once initialized, the `tree_explainer.decision_tree_to_text()` function is used to extract the decision rules of the tree in **natural language format**.

This function:

- Traverses each branch of the decision tree to identify conditions (e.g., "Feature X <= Y").
- Compiles these conditions into human-readable rules for every possible path in the tree.
- Outputs the rules as text, including the predicted class and its probability at the leaf nodes.

"""

# Initialize the TreeSplanerClassifier
tree_explainer = TreeSplanerClassifier(
    clf,
    feature_names=X.columns.tolist(),
    target_names=['Dropout', 'Enrolled', 'Graduate']
)

# Extract decision tree rules in text format
decision_rules = tree_explainer.decision_tree_to_text()
decision_rules[:1000]

"""The decision rules show how the model predicts the student outcome using several conditions. For example, if a student does not have a scholarship, is 22.5 years or younger, is not a debtor, has a previous qualification grade ≤ 140.5, and meets several background conditions such as low mother’s qualification, specific parental occupation, and application order ≤ 2.5, the model predicts the student will Graduate with a probability of 1.0.

However, if the same conditions are met but the inflation rate is higher than −2.0, the prediction changes to Dropout with a probability of 1.0. This shows that the decision tree combines academic performance, financial status, family background, and economic factors to determine the final class. The rules illustrate how multiple variables interact to predict whether a student will graduate or drop out.
"""

# Generate predictions for some test samples and explain in text format
test_sample_predictions = tree_explainer.build_text_prediction(X_test[:1].values)
test_sample_predictions

"""This decision rule explains one specific path in the decision tree that leads to the prediction Graduate. According to this rule, if a student does not have a scholarship, the unemployment rate is high (> 8.25), the student has debt, is female (Gender ≤ 0.5), and enrolled at age ≤ 24.5, along with several academic conditions such as previous qualification grade and admission grade within certain ranges, the model predicts that the student will Graduate with a probability of 1.0.

This rule shows that the prediction is based on a combination of academic performance (grades), demographic factors (age and gender), financial status (debtor), and economic indicators (unemployment rate, inflation, GDP). When all these conditions are satisfied, the decision tree strongly classifies the student as Graduate.
"""

# Extract branch impurity information
branch_impurities = tree_explainer.branch_impurity()
branch_impurities[:500]

plt.figure(figsize=(20, 10))  # Adjust figure size for better readability
plot_tree(
    clf,
    feature_names=X.columns.tolist(),  # Feature names for nodes
    class_names=['Dropout', 'Enrolled', 'Graduate'],  # Target class names
    filled=True,  # Color nodes based on class or feature importance
    rounded=True  # Round node boxes for aesthetics
)
plt.title("Decision Tree Visualization")
plt.show()

"""The Decision Tree visualization represents how the model makes predictions for the target classes Dropout, Enrolled, and Graduate using multiple features. The tree begins with a root node, which splits the dataset based on the most important feature. From there, the data is repeatedly divided into smaller branches based on conditions such as scholarship status, academic grades, age at enrollment, debtor status, admission grade, and economic indicators like unemployment rate or inflation.

Each branch represents a decision rule, and the tree continues splitting until it reaches leaf nodes, which show the final predicted class. The color intensity of the nodes indicates the dominant class in that group, while the values inside each node represent the number of samples and class distribution. Because the tree is very deep and contains many branches, it suggests that the model is complex and may be overfitting the training data, meaning it tries to capture too many specific patterns. The visualization shows how the model uses a combination of academic performance, financial status, demographic characteristics, and economic factors to predict student outcomes.
"""

# Extract all paths from the TreeSplanerClassifier
all_paths = tree_explainer.find_paths_from_root()

# Prepare data for tabular visualization
rules_data = []
for path in all_paths:
    conditions = []
    for node in path[:-1]:  # Exclude the leaf node
        if node in tree_explainer.children_right:
            eq = ">"
        else:
            eq = "<="
        condition = f"{tree_explainer.feature_names[tree_explainer.feature[node]]} {eq} {round(tree_explainer.threshold[node], 2)}"
        conditions.append(condition)

    # Extract class and probability at the leaf node
    leaf_node = path[-1]
    predicted_class = tree_explainer.target_names[np.argmax(tree_explainer.value[leaf_node][0])]
    probability = round(np.max(tree_explainer.value[leaf_node][0]) / np.sum(tree_explainer.value[leaf_node][0]), 3)

    # Append to rules_data
    rules_data.append({
        "Rule": " AND ".join(conditions),
        "Predicted Class": predicted_class,
        "Probability": probability
    })

# Convert to DataFrame
rules_df = pd.DataFrame(rules_data)
rules_df.head(10)

"""The rule table shows several decision rules generated by the Decision Tree model. Each rule represents a specific combination of conditions based on features such as Scholarship holder, Age at enrollment, Debtor status, grades, and other background factors. When all the conditions in a rule are satisfied, the model predicts a specific class such as Graduate, Dropout, or Enrolled.

In this table, every rule has a probability of 1.0, which means that for the data samples that follow that rule, the model is fully confident about the predicted class. Some rules predict Graduate, while others predict Dropout or Enrolled, depending on the combination of conditions. This rule-based output helps explain how the decision tree translates feature conditions into final predictions and makes the model more interpretable.
"""

rules_df['Rule'].iloc[0]

"""This decision rule represents one path in the decision tree used to predict the student outcome. According to this rule, if a student does not have a scholarship, is 22.5 years old or younger at enrollment, is not a debtor, and gender ≤ 0.5, along with having previous qualification grade ≤ 140.5, mother’s qualification ≤ 0, mother’s occupation ≤ 1.5, application order ≤ 2.5, and father’s occupation ≤ 6, then the model follows this branch of the tree to determine the final prediction.

This rule shows that the prediction is based on a combination of demographic background, academic performance, and family socio-economic factors, which together influence the model’s decision about the student’s outcome.
"""

# Summarize key rules
def summarize_rules(clf, feature_names):
    rules = export_text(clf, feature_names=feature_names)
    print("Decision Tree Rules Summary:")
    print(rules[:2000])  # Print the first 2000 characters for brevity
    return rules

# Example usage
rules_summary = summarize_rules(clf, X.columns.tolist())

"""The Decision Tree Rules Summary shows the hierarchical process the model uses to classify student outcomes. The first and most important split is based on Scholarship holder, meaning the model first checks whether the student receives a scholarship. If the student does not have a scholarship, the model then evaluates Age at enrollment, followed by Debtor status, Gender, and Previous qualification grade. These conditions indicate that financial status, demographic characteristics, and prior academic performance are key factors in determining the student’s predicted outcome.

Further branches consider family background variables such as Mother’s qualification, Mother’s occupation, and Father’s occupation, along with Application order and economic indicators like GDP and Unemployment rate. The tree continues splitting into deeper branches (some truncated in the summary) until it reaches a final class prediction. In the output, class 0, 1, and 2 correspond to the target categories (Dropout, Enrolled, and Graduate). The rules show that the model combines academic performance, financial status, family background, and economic conditions to predict student success.

Extra_Exercise
"""

# Step 1: Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Step 2: Load the iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

# Step 3: Introduce a leakage feature
# Add a column that directly correlates with the target (e.g., y + random noise)
X['leakage_feature'] = y + np.random.normal(0, 0.1, size=len(y))

# Step 4: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train the Decision Tree
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

# Step 6: Evaluate the model
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with Leakage: {accuracy:.2f}")

# Step 7: Plot feature importance
feature_importances = clf.feature_importances_
plt.figure(figsize=(10, 6))
plt.barh(X.columns, feature_importances, color='skyblue')
plt.title("Feature Importance with Leakage")
plt.xlabel("Importance")
plt.ylabel("Features")
plt.show()

# Step 1: Import necessary libraries
from sklearn.ensemble import RandomForestClassifier

# Step 2: Train a Random Forest WITH leakage
rf_with_leakage = RandomForestClassifier(n_estimators=100, random_state=42)
rf_with_leakage.fit(X_train, y_train)

# Step 3: Train a Random Forest WITHOUT leakage
X_train_no_leakage = X_train.drop(columns=['leakage_feature'])
X_test_no_leakage = X_test.drop(columns=['leakage_feature'])
rf_no_leakage = RandomForestClassifier(n_estimators=100, random_state=42)
rf_no_leakage.fit(X_train_no_leakage, y_train)

# Step 4: Evaluate both models
y_pred_with_leakage = rf_with_leakage.predict(X_test)
y_pred_no_leakage = rf_no_leakage.predict(X_test_no_leakage)

accuracy_with_leakage = accuracy_score(y_test, y_pred_with_leakage)
accuracy_no_leakage = accuracy_score(y_test, y_pred_no_leakage)

print(f"Accuracy with Leakage: {accuracy_with_leakage:.2f}")
print(f"Accuracy without Leakage: {accuracy_no_leakage:.2f}")

# Step 5: Plot feature importance for both models
plt.figure(figsize=(12, 6))

# With leakage
plt.subplot(1, 2, 1)
plt.barh(X.columns, rf_with_leakage.feature_importances_, color='salmon')
plt.title("Feature Importance WITH Leakage")
plt.xlabel("Importance")
plt.ylabel("Features")

# Without leakage
plt.subplot(1, 2, 2)
plt.barh(X_train_no_leakage.columns, rf_no_leakage.feature_importances_, color='lightgreen')
plt.title("Feature Importance WITHOUT Leakage")
plt.xlabel("Importance")
plt.ylabel("Features")

plt.tight_layout()
plt.show()